### ISSUE TITLE
How do I start Ride on Win10 after deleting the desktop shortcut?

### ISSUE THREAD

**Issue by norberturkiewicz** [Dyalog/ride#752] opened 2021-07-27 14:50 UTC
### Describe the issue you are having
Cannot start RIDE after deleting the default desktop shortcut.  RIDE does not show up in the start menu apps or by searching in the start bar.  It does show up in Programs. 

![image](https://user-images.githubusercontent.com/5807754/127175932-28a8ff12-40af-481a-9fec-0d9665c7e6b6.png)
![image](https://user-images.githubusercontent.com/5807754/127176217-276b69dc-40e2-4c3a-abb1-917c43411160.png)

If this is a repeat of #669, please delete but that issues as not been update since it was created.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### Paste the contents of Help → About (Shift+F1)
N/A

**Comment by Masterquiz** [comment] 2021-08-11 16:07
Did you try searching in Downloads\Ride-4.3 the .exe file?

**Comment by Masterquiz** [comment] 2021-08-11 16:07
> ### Describe the issue you are having
> Cannot start RIDE after deleting the default desktop shortcut. RIDE does not show up in the start menu apps or by searching in the start bar. It does show up in Programs.
> 
> ![image](https://user-images.githubusercontent.com/5807754/127175932-28a8ff12-40af-481a-9fec-0d9665c7e6b6.png)
> ![image](https://user-images.githubusercontent.com/5807754/127176217-276b69dc-40e2-4c3a-abb1-917c43411160.png)
> 
> If this is a repeat of #669, please delete but that issues as not been update since it was created.
> 
> ### Did you connect to an already running interpreter or start the interpreter from RIDE?
> N/A
> 
> ### How do you reproduce the issue?
> ### Paste the contents of Help → About (Shift+F1)
> N/A

Did you try searching in Downloads\Ride-4.3 the .exe file?

**Comment by abrudz** [comment] 2021-08-11 16:16
Mine is located under C:\Users\<name>\AppData\Local\Programs\Dyalog

**Comment by e9gille** [comment] 2021-09-28 11:09
We currently don't create a shortcut for RIDE in the Start menu. @JasonDyalog will help me resolve that.

**Comment by dyaandys** [comment] 2021-12-20 14:24
I think this is also "Do not see RIDE in the Start menu on Windows 11" .. which also applied to Windows 10.

**Comment by abrudz** [comment] 2023-07-19 09:11
Duplicate of #669

**Closed by abrudz** 2023-07-19 09:11 UTC
Labels: Windows
