### ISSUE TITLE
HTML User Command gives DOMAIN ERROR

### ISSUE THREAD

**Issue by rikedyp** [Dyalog/ride#657] opened 2021-02-15 12:30 UTC
### Describe the issue you are having
Using ]html gives DOMAIN ERROR in RIDE

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start from RIDE

### How do you reproduce the issue?
`]html 'hello'`

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.3.3463
  Platform: Linux x86_64
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "zoom":"5",
    "selectedExe":"/opt/mdyalog/18.1/64/unicode/mapl"
  }

Interpreter:
  Version: 18.1.40044
  Platform: Linux-64
  Edition: Unicode/64
  Date: Feb 15 2021 at 03:37:47

```

**Comment by abrudz** [comment] 2021-02-18 16:59
This was caused by an interpreter behavioral change and has been addressed in the APL code.

**Closed by abrudz** 2021-02-18 16:59 UTC
