### ISSUE TITLE
Infinite loop on "Connect…" to WSL APL

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#891] opened 2022-08-04 09:59 UTC
I start like this:
```batch
@START "WSL" /MIN /D "%HOMEPATH%\Documents\Dyalog APL Files" /B wsl.exe dyalog RIDE_INIT=SERVE:*:4502 APLCORENAME=/mnt/c/tmp/aplcore DYALOG_LINEEDITOR_MODE=1
@SET RIDE_CONNECT=localhost:4502
@START "RIDE" /D "%HOMEPATH%\Documents\Dyalog APL Files" "C:\Users\Adam\AppData\Local\Programs\Dyalog\Ride-4.4\Ride-4.4.exe"
```
And then File>Connect… gives:
![image](https://user-images.githubusercontent.com/10961427/182819815-627c180b-c060-45d1-b443-e784d10d2e99.png)
Hitting <kbd>OK</kbd> appears to close RIDE and restart it, only to come right back to that state, with no way to quit.
```
IDE:
  Version: 4.4.3687
  Platform: Win32
  Date: 2022-02-23 13:44:34 +0100
  Git commit: a3d8123cfb690ead493e261ccced59407db04c64
```

**Comment by e9gille** [comment] 2022-08-17 06:30
Caused by inherited RIDE_CONNECT settings. Fixed in 23d70914e6f238438ea35948ae3af8bf2f5d9963

**Closed by e9gille** 2022-08-17 06:30 UTC
Labels: bug
