### ISSUE TITLE
RIDE_EDITOR=gvim does not work.  It does not get the changes made in gvim into Dyalog

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#542] opened 2019-06-06 12:12 UTC
### Describe the issue you are having
in RIDE 
)ed foo

gvim editor opens up.

I make some changes and close the editor with :wq

editor closes, but the foo in dyalog does not have any of the changes made

(gedit works OK, as does vim if I use a script to call it in a new xterm).

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter 

### How do you reproduce the issue?
in a command shell:
export RIDE_EDITOR=gvim
ride
Choose to Start Dyalog 17.1 unicode 64-bit

### Paste the contents of Help → About (Shift+F1)

IDE:
  Version: 4.2.3432
  Platform: Linux x86_64
  Date: 2019-05-24 12:10:06 +0100
  Git commit: 3be9ea797d360ddb13d87752f36752316f1e19fa
  Preferences:{

  }

Interpreter:
  Version: 17.1.36353
  Platform: Linux-64
  Edition: Unicode/64
  Date: May 30 2019 at 01:11:22

**Comment by abrudz** [comment] 2022-07-12 08:02
See  #885

**Comment by xpqz** [comment] 2023-06-08 08:52
Closing as dupe of #885

**Closed by xpqz** 2023-06-08 08:52 UTC
