### ISSUE TITLE
Multiple Trace Windows open simultaneously do not display as expected

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#198] opened 2017-07-24 11:08 UTC
### Describe the issue you are having
Function contains an error. Run it multiple times and get multiple trace windows. Display of these is peculiar. I get two on the screen, one above the other, then multiple other ones hidden and unreachable until I close the others.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Already running

### How do you reproduce the issue?
)ed foo
give foo contents of jot
run foo - trace window is displayed
run foo again - second trace window is displayed (was expecting a second tab on the existing trace window)
run foo again - no further windows are displayed and no tab is added to either existing window. Closing one of the two windows now displays the third trace window.
Repeat ad nauseum.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2849
  Platform: Win32
  Date: 2017-07-20 11:23:40 +0100
  Git commit: ff806cb588cd1c8ae908949e27211d64cbf565e9
  Preferences:{
    "indent":"6",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⍴⌹○~!? |⌈⌊⍉⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩ /\\⌿⍀ ,⍪⌽⊖ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "lineNums":"0",
    "zoom":"-1"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by jayfoad** [comment] 2017-07-28 10:39
I'm not sure we should ever have more than one trace window (or tab). I don't think this happens in the ODE (does it?).

**Comment by flouc001** [comment] 2017-08-03 09:22
@FionaDyalog @jayfoad I'm having trouble reproducing this. I am running with the latest production interpreter. I have tried on Linux and Windows and cannot get a second trace window to pop up regardless of my interpreter trace configuration.

**Comment by FionaDyalog** [comment] 2017-08-03 13:12
I've tried with the latest version:
IDE:
  Version: 4.1.2906
  Platform: Win32
  Date: 2017-08-03 09:43:13 +0100
  Git commit: e904a9eb51a9a01b21f809e2b0e0e889ea48c825
  Preferences:{

  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

I can't reproduce it there. However, this is RIDE 4.1. It ought to be sorted in RIDE 4.0.

**Comment by flouc001** [comment] 2017-08-03 13:20
@FionaDyalog Sure, I have tried with both RIDE4.1 and RIDE4 and could not reproduce this in either.

**Comment by jayfoad** [comment] 2017-08-10 09:30
I can't reproduce this with RIDE 4.0 on Linux.

**Comment by e9gille** [comment] 2017-11-02 11:06
Closing as no update received in months. If this is still an issue we can reopen it.

**Closed by e9gille** 2017-11-02 11:06 UTC
