### ISSUE TITLE
Opening an Edit window is behaving oddly

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#203] opened 2017-07-25 11:01 UTC
### Describe the issue you are having
Opening an Edit window for a function when the debug and Trace windows are open means the Edit window opens on the left (expected the right), the Edit window doesn't sit above the Trace window (which I expected it to) and the Session window has been shrunk to a tiny narrow unreadable strip in the middle!

Start with:
![image](https://user-images.githubusercontent.com/13313372/28569106-4f52afb0-7130-11e7-9d82-d0205259bfc3.png)

Open an Edit window:
![image](https://user-images.githubusercontent.com/13313372/28569121-6904d294-7130-11e7-9801-8999b8adea8d.png)
### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
See "Describe the issue you are having". Managed to reproduce after closing and restarting RIDE.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2849
  Platform: Win32
  Date: 2017-07-20 11:23:40 +0100
  Git commit: ff806cb588cd1c8ae908949e27211d64cbf565e9
  Preferences:{
    "indent":"6",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⍴⌹○~!? |⌈⌊⍉⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩ /\\⌿⍀ ,⍪⌽⊖ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "lineNums":"0",
    "zoom":"-1",
    "dbg":"1"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by flouc001** [comment] 2017-08-03 11:11
Fix in place in branch iss203, awaiting testing before merge.

**Comment by jayfoad** [comment] 2017-08-10 09:46
@FionaDyalog I can't reproduce the original issue, so can you please test the fix in U:\builds\ride\iss203\latest ?

**Comment by FionaDyalog** [comment] 2017-08-10 13:03
Using that version the Edit window now opens in the correct place. However, I would expect the Trace window to span the entire session but the Edit window is full height instead, forcing the Trace window to be beneath the Session window only..

![image](https://user-images.githubusercontent.com/13313372/29171428-7d0b015e-7dd4-11e7-8a0a-58b84c1753b3.png)

**Comment by flouc001** [comment] 2017-10-05 11:17
Any update on this or can I merge the changes in and close the issue?

**Comment by jayfoad** [comment] 2018-04-24 15:35
> Using that version the Edit window now opens in the correct place. However, I would expect the Trace window to span the entire session but the Edit window is full height instead, forcing the Trace window to be beneath the Session window only.

I think that's the way it's supposed to work. And it's the way the ODE seems to work.

**Closed by jayfoad** 2018-04-24 15:35 UTC
