### ISSUE TITLE
About shortcut does not work from connect screen

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#248] opened 2017-10-17 09:33 UTC
### Describe the issue you are having
While connected to an interpreter, the About box can be brought up with Shift+F1. This does not work despite the About box being available through a mouse click on a button. However, the template for Git issues says to get there using Shift+F1, which clearly does not work.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
No.

### How do you reproduce the issue?
From connect screen, press Shift+F1.

### Paste the contents of Help → About (Shift+F1)
Well… that doesn't work! :-)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "zoom":"5"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by jayfoad** [comment] 2017-10-17 09:36
Duplicate of #227.

**Closed by jayfoad** 2017-10-17 09:36 UTC
