### ISSUE TITLE
Session context menu is truncated by docked trace window

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#501] opened 2018-11-20 13:06 UTC
Docked windows.

      ⎕fx'foo' '⍪⍳40' '⍝'
      foo
      foo<TC>
Select text on one of the bottom 2 or 3 lines of the visible session
Right click
Much of the context menu is not visible .. certainly no way to select "Copy"

Is this related to 466 ?

IDE:
  Version: 4.2.3379
  Platform: Win32
  Date: 2018-10-30 08:27:53 +0000
  Git commit: 7b046167ca6cab996fcd7753e41102da5fa1ea43
  Preferences:{
    "kbdLocale":"en_US",
    "otherExe":"/opt/mdyalog/18.0/64/unicode/p8/mapl",
    "wse":"1"
  }

Interpreter:
  Version: 18.0.34813
  Platform: AIX-64
  Edition: Unicode/64
  Date: Nov 20 2018 at 00:35:15

**Comment by dyaandys** [comment] 2018-11-21 13:49
The same is true of the "box" which shows the value of objects; in the tracer I hovered over a name on line[0] of the function, and the contents were clipped to the bottom line and 1/2 of the previous line.

**Comment by e9gille** [comment] 2018-11-26 20:54
Duplicate of #487

**Closed** 2018-11-26 20:54 UTC
