### ISSUE TITLE
SSH connection features need better diagnostics

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#118] opened 2017-03-07 10:07 UTC
# RIDE Issue Report

### Describe the issue you are having
The features for connecting via SSH don't provide error messages. If you click "Get list of interpreters via SSH" you get a stony silence, and if you are lucky the dropdown is populated with a list. If not, no response of any kind.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Starting from RIDE via ssh.

### How do you reproduce the issue?
The SSH functionality seems a bit flaky... It didn't work a bunch of times, and then suddenly it started working, and I didn't change anything (honest). At the same time I was able to consistently create SSH connections using PuTTY. Since I wasn't getting any diagnostic output it was hard to figure out what was going on.

### Paste the contents of Help → About (Shift+F1)
March 6th "git get".

**Comment by jayfoad** [comment] 2017-03-14 09:45
The thing about "Get list of interpreters via SSH" is a duplicate of #130 (or vice versa). For the "seems a bit flaky" I think you'll need to provide more specific examples, or let someone take a look when it's going wrong.

**Closed by jayfoad** 2017-03-14 09:45 UTC

**Comment by mkromberg** [comment] 2017-03-14 10:01
I would say that I have only seen this functionality work sporadically, it fails silently most of the time, even at times where launching an interpreter using the same credentials works. There are no error messages and I don't believe the is any logging, so I don't know how to provide further information. Of course, this morning when I test it, it works fine - but I don't know how I can provide additional information the next time it fails. I think the ssh code needs some logging added so that there is a way to see what is happening / failing.
