### ISSUE TITLE
Autocomplete label is cutoff in the center

### ISSUE THREAD

**Issue by norberturkiewicz** [Dyalog/ride#334] opened 2018-04-11 15:36 UTC
### Describe the issue you are having
The autocomplete label is cutoff by the debugger resize slider.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connected to an existing remote session.  Windows Ride and Linux interpreter

### How do you reproduce the issue?
Stop a function during execution and type in a letter to start autocomplete

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2938
  Platform: Win32
  Date: 2017-10-20 11:26:37 +0100
  Git commit: ce6702217f56f7bc543951a8a318b6acf2904b06
  Preferences:{
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: 16.0.32456
  Platform: Linux-64
  Edition: Unicode/64
  Date: Mar 13 2018 at 03:31:46

![image](https://user-images.githubusercontent.com/5807754/38627220-16d3693e-3d74-11e8-9bb7-d294fbf9cefb.png)

**Comment by jayfoad** [comment] 2018-04-16 15:36
I can reproduce this in master but not in the monaco branch. We're hoping to merge monaco back into master real soon now, so that'll fix it.

**Comment by e9gille** [comment] 2018-04-19 21:01
in master it doesn't cut it in half, but with a docked tracer under the session it may still pop up the list under the cursor and therefore only show the first line in the list. It looks like the editor checks the window bounds rather than its own when deciding if the list will fit under the cursor and therefore gets it wrong.

**Comment by e9gille** [comment] 2018-05-06 07:37
Closing, please shout if still and issue.

**Closed by e9gille** 2018-05-06 07:37 UTC
