### ISSUE TITLE
System command output such as from )lib is too long in Dyalog 19.0 under RIDE 4.5

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#1222] opened 2024-03-22 11:09 UTC
### Describe the issue you are having
)lib output is too long.  It should wrap to the size of the window as it does in ODE on MS Windows.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Start RIDE-4.5
Ensure that ⎕pw←79
Make the RIDE Window wide enough so that it could display 120 characters on one line if I wanted.
)lib

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.5.4097
  Electron: 26.6.9
  Chrome: 116.0.5845.228
  Node: 18.16.1
  Platform: Linux x86_64
  Date: 2024-02-23 15:24:25 +0100
  Git commit: 9fb313638328832b51012bd75b2523a8d97f4509
  Preferences:{
    "defaultConfig":"v19.0",
    "kbdLocale":"en_GB",
    "presetsCreated":"[\"/opt/mdyalog/19.0/64/unicode/mapl\",\"/opt/mdyalog/18.2/64/unicode/mapl\",\"/opt/mdyalog/17.0/64/unicode/mapl\"]"
  }

Interpreter:
  Version: 19.0.48958
  Platform: Linux-64
  Edition: Unicode/64
  Date: Mar  6 2024 at 11:16:30

```

This is what we get in the RIDE window.  The line beginning with apl2in.dws ends with smdemo.dws and is 298 characters wide.
      ⎕pw
79
      80⍴'a'
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      a
      )lib
/opt/mdyalog/19.0/64/unicode/ws
        apl2in.dws      apl2pcin.dws    buildse.dws     conga.dws       ddb.dws         dfns.dws        display.dws     eval.dws        fonts.dws       ftp.dws         groups.dws      isolate.dws     loaddata.dws    max.dws min.dws ops.dws         quadna.dws      salt.dws        sharpplot.dws   smdemo.dws      
        smdesign.dws    smtutor.dws     sqapl.dws       tube.dws        
        tutor.dws       util.dws        xfrcode.dws     xlate.dws       
/opt/mdyalog/19.0/64/unicode/Samples/OO4APL
        Chapter9.dws    ComponentFile.dws       ExcelWorkBook.dws       
        Monthly.dws     MonthlyAfter5.dws       OOTools.dws     PlanBook.dws            PlanBookFinal.dws       Queue.dws       Random.dws      TimeSeries.dws          derivedgui.dws  dotnet.dws      guitools.dws

**Comment by dyavc** [comment] 2024-03-22 11:21
Dyalog 18.2 just makes its )lib output 80 chars regardless of the size of the RIDE window.

**Comment by dyavc** [comment] 2024-05-07 14:48
I have also logged this against Dyalog, mantis issue 21356.

**Comment by dyavc** [comment] 2024-06-04 10:04
John has looked at 21356 and says that "I think 21356 will need to be fixed RIDE side" and "I think we are giving ride all the information it needs".

**Comment by dyaandys** [comment] 2024-06-19 11:46
21356 was marked as a duplicate of 21426 which was a change to the interpreter in 19.0 and 20.0.  So this RIDE issue can now be closed.

**Closed by dyaandys** 2024-06-19 11:46 UTC
