### ISSUE TITLE
)ed asks for variable name when saving to disk

### ISSUE THREAD

**Issue by razetime** [Dyalog/ride#663] opened 2021-02-22 12:46 UTC
### Describe the issue you are having
When I choose the "Only Save File To Disk" option when saving a file in `)ed`, it also asks me for a variable name.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
I started the interpreter from RIDE.

### How do you reproduce the issue?
- Create a new file with `)ed "<insert location here>"`
- Right click → Fix
- click on "Only Save File To Disk"

<img src="https://i.stack.imgur.com/L2UcP.gif"></img>

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.3.3463
  Platform: MacIntel
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "colourScheme":"Francisco Goya (1)",
    "colourSchemes":"[{\"name\":\"Francisco Goya (1)\",\"theme\":\"dark\",\"styles\":\"asgn=fg:ff0 com=fg:b,I cur=bc:f00 dfn2=fg:eb4 dfn3=fg:c79 dfn4=fg:cd0 dfn5=fg:a0d dfn=fg:a7b diam=fg:ff0 err=fg:f00,bg:822,bgo:0.5,B fn=fg:0f0 idm=fg:0f0 glb=bgo:0.75,U,bg:0ff kw=fg:aa2 lbl=U,bg:642,bgo:0.5 lnum=fg:b94,bg:010,bgo:0 mod=bg:7,bgo:0.5 mtch=fg:0,bg:0,bgo:0 norm=fg:9c7,bg:0,bgo:1 num=fg:a8b op1=fg:d95 op2=fg:fd6 sel=bg:048,bgo:0.5 semi=fg:8 sqbr=fg:8 srch=bg:b96,bgo:0.75,fg:0 str=fg:dae tc=bg:1,bgo:1 tcpe=bg:2,bgo:1 zld=fg:d9f,B scmd=fg:0ff ucmd=fg:f80,B vtip=bg:733,fg:ff0,bgo:1,bc:900 vtt=bc:f80 ca=bg:828282,bgo:1,fg:0f0 cm=bg:0,bgo:1,fg:0f0 cv=bg:f,bgo:1,fg:0 cvv=bg:0,bgo:1,fg:0ff ma=bg:828282,bgo:1,fg:0ff na=bg:828282,bgo:1,fg:f qor=bg:f00,bgo:1,fg:f dc=bg:3,bgo:1\"}]",
    "floating":"1",
    "kbdLocale":"en_US_Mac",
    "keys":"{\"FX\":[\"Cmd-S\"]}",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤⍥@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "zoom":"1"
  }

Interpreter:
  Version: 18.0.38756
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jul 16 2020 at 01:08:20

```

**Comment by e9gille** [comment] 2021-02-22 15:07
Duplicate of #495

**Closed by e9gille** 2021-02-22 15:07 UTC
Labels: bug
