### ISSUE TITLE
The font size for language bar tool tips is not modifiable

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#188] opened 2017-07-07 10:35 UTC
### Describe the issue you are having
The font size for language bar tool tips is not modifiable

### Did you connect to an already running interpreter or start the interpreter from RIDE?
connected

### How do you reproduce the issue?
resize the session font - language bar tooltips stay the size they were. Like being shouted at!

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2836
  Platform: Win32
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032
  Preferences:{
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "lineNums":"0",
    "wse":"1",
    "zoom":"-1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by jayfoad** [comment] 2017-07-13 15:42
Very similar to #34.

**Comment by flouc001** [comment] 2017-10-05 08:41
Duplicate of #34 please see the fix in branch iss34.

**Comment by flouc001** [comment] 2017-10-05 08:41
Please see the fix in branch iss34

**Comment by jayfoad** [comment] 2017-10-05 08:51
Looks good to me (but I think we should also do #146).

**Comment by flouc001** [comment] 2017-10-05 10:58
@jayfoad looking into #146 now :)

**Closed** 2017-10-05 11:18 UTC
Labels: enhancement, P3
