### ISSUE TITLE
Need a way to query session window size

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#232] opened 2017-09-24 12:33 UTC
### Describe the issue you are having
The ]rows user command needs to query how many rows and columns the session window has.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

**Comment by jayfoad** [comment] 2018-05-01 12:00
Duplicate of #378.

**Closed by jayfoad** 2018-05-01 12:00 UTC
Labels: enhancement
