### ISSUE TITLE
Confirmation dialogs do not have focus

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#121] opened 2017-03-08 09:30 UTC
E.g. when modifying a SALTed object, pressing Esc pops up a dialog asking for confirmation. Pressing Enter to confirm inserts a linebreak in the editor rather than pressing "YES" (is in IDE).

**Comment by jayfoad** [comment] 2017-03-08 10:21
Duplicate of #90 ?

**Comment by abrudz** [comment] 2017-03-08 10:28
No, but related.

**Closed** 2017-04-05 11:21 UTC
