### ISSUE TITLE
File > Open menu item should only be present for local sessions spawned by RIDE

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#395] opened 2018-05-11 08:19 UTC
### Describe the issue you are having
File > Open does nothing

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Launch Session.
Go to File > Open.
Nothing happens.

I have tried restarting both the interpreter and RIDE and can reproduce this every time.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3258
  Platform: Win32
  Date: 2018-05-09 21:37:18 +0200
  Git commit: a2dd832e5712e4dcf8d7f69d4f7e3a561d5123f4
  Preferences:{
    "colourScheme":"Default (1)",
    "colourSchemes":"[{\"name\":\"Default (1)\",\"theme\":\"light\",\"styles\":\"asgn=fg:00f com=fg:088 dfn=fg:00f diam=fg:00f err=fg:f00 fn=fg:008 idm=fg:008 kw=fg:800 lnum=fg:008,bg:f,bgo:0 mod=bg:7,bgo:0.25 mtch=bg:ff8,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 op1=fg:00f op2=fg:00f par=fg:00f quad=fg:808 qdl=fg:c0c sel=bg:48e,bgo:0.5 semi=fg:00f sqbr=fg:00f srch=bg:f80,bgo:0.5 str=fg:088 tc=bg:d,bgo:1 tcpe=bg:c8c8c8,bgo:1 trad=fg:8 var=fg:8 zld=fg:008 scmd=fg:00f ucmd=fg:00f vtt=bg:ff0 ca=bg:828282,bgo:1,fg:0f0 cm=bg:0,bgo:0.1,fg:0f0 cv=bg:f,bgo:1,fg:0 cvv=bg:0,bgo:1,fg:0ff ma=bg:828282,bgo:1,fg:0ff na=bg:828282,bgo:1,fg:f qor=bg:f00,bgo:1,fg:f\"}]",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "squiggleTips":"1",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.33034
  Platform: Windows-64
  Edition: Unicode/64
  Date: May  9 2018 at 09:31:12

**Comment by FionaDyalog** [comment] 2018-05-11 10:50
Same issue with local interpreter on Linux

IDE version 4.1.3261
Platform: Linux x86_64
Date: 2018-05-11 00:20:40 +0200
Git commit: a11154957eb6f90207d42a66e2b3d80b5b852094

**Comment by e9gille** [comment] 2018-05-15 07:42
@FionaDyalog What Linux OS are you testing this on?

**Comment by FionaDyalog** [comment] 2018-05-15 07:46
@e9gille 

Ubuntu 16.0.4 (accessed through VirtualBox)

**Comment by e9gille** [comment] 2018-05-28 10:52
I've just installed and tested on 16.0.4.4  and it seems to work fine, both in the current master and the one you reported the issue in.

Can you check if your OS is patched and updated? (Run lsb_release -a to check the full version number). I don't know how else to debug this.

**Comment by FionaDyalog** [comment] 2018-05-29 13:05
Issue still exists.
Not sure what you mean with the "lsb_release -a" instruction – I'm on a Windows machine for both the interpreter and RIDE!

IDE:
  Version: 4.1.3321
  Platform: Win32
  Date: 2018-05-27 22:39:34 +0200
  Git commit: 260f7337e44a6302d558cc052403ae657702d76b

Interpreter:
  Version: 17.0.33166
  Platform: Windows-64
  Edition: Unicode/64
  Date: May 23 2018 at 20:07:44

**Comment by jayfoad** [comment] 2018-05-29 13:11
I think Fiona was connecting to a running interpreter (both on Linux and Windows). OWS() does nothing if !D.lastSpawnedExe. I think Fiona's complaint is that you shouldn't have a menu item that does nothing: either it should not be there at all, or it should work, or it should give some kind of error message.

**Comment by FionaDyalog** [comment] 2018-05-29 13:13
I have no idea what this option is supposed to do or when I would use it – without knowing what configuration I need to activate it I can’t test/use/document it!

**Comment by e9gille** [comment] 2018-05-29 13:54
@jayfoad  Thank you very much, once again I got the wrong end of the stick. I will try to read the reports more carefully in the future. Sorry @FionaDyalog, I know understand what the issue is and will see what I can do about it.

**Comment by e9gille** [comment] 2021-02-22 21:30
Fixed by #659

**Closed** 2021-02-22 21:30 UTC
