### ISSUE TITLE
clicking x on last tab of the edit window does not close the editor

### ISSUE THREAD

**Issue by geoffstreeter** [Dyalog/ride#93] opened 2017-02-20 14:42 UTC
This may be connected to the issue with <EP> not closing the last tab in the editor.

**Comment by dyaandys** [comment] 2017-02-20 16:07
I think this may be a duplicate of #89 .. Editor: clicking on X on a tab may merely alter the order of the tabs.

**Comment by e9gille** [comment] 2017-06-14 13:25
I can't replicate this. I'll close it until proven still an issue.

**Closed by e9gille** 2017-06-14 13:25 UTC
