### ISSUE TITLE
Ability to remove lines from session log as in ODE

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#64] opened 2017-01-28 16:07 UTC
Selecting lines and pressing Ctrl+Del in ODE will remove the selected lines from the session-log after confirming:
![2017-01-28_17-03-37](https://cloud.githubusercontent.com/assets/5645494/22397883/f609712c-e57b-11e6-980a-9f1b9d7540e4.png)

RIDE does not do this - instead it just restores the lines when user presses Enter. I would like the same behaviour as in ODE.

**Comment by jayfoad** [comment] 2017-01-28 18:44
Duplicate of #33.

**Closed by jayfoad** 2017-01-28 18:44 UTC
