### ISSUE TITLE
WS explorer window does not update properly

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#154] opened 2017-04-25 12:03 UTC
### Describe the issue you are having
The workspace explorer window does not update properly

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Attached to running

### How do you reproduce the issue?
In a clear workspace:
f←{}
Open # in the workspace explorer and f is present
g←{}
*** g does not appear in the WS explorer ***
Close/reopen # in the WS explorer and it is present
)CLEAR
'#' is shown empty and collapsed

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2787
  Platform: Linux x86_64
  Date: 2017-04-24 16:41:40 +0100
  Git commit: b4cdc0af241089f1181ca0e9c68ae0cb2f923291
  Preferences:{
    "dbg":"1",
    "kbdLocale":"en_GB",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.29813
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr 25 2017 at 09:26:51

**Comment by jayfoad** [comment] 2017-04-25 12:42
Duplicate of #18.

**Closed by jayfoad** 2017-04-25 12:42 UTC
