### ISSUE TITLE
About button on Connection page overlaps scroll bar

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#226] opened 2017-08-23 11:53 UTC
### Describe the issue you are having
![image](https://user-images.githubusercontent.com/10961427/29614420-fc733056-8801-11e7-90d2-23bd6fa6b3bf.png)

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
Start RIDE. Resize window vertically until scrollbar appears.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2634
  Platform: Win32
  Date: 2017-02-10 00:27:35 +0100
  Git commit: 5c74ac580aa5de9da4515cd01e4bf57341faaa86
  Preferences:{
    "kbdLocale":"en_US",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "title":"{WSID} {VER}",
    "wse":"1",
    "zoom":"3"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by JasonRivers** [comment] 2017-08-23 12:31
You stated the version is 4.0.2634 - This can't be true as this is the Ride 4.1 (master) connect window. The latest Ride 4.0 is 4.0.2850, or 4.0.2860 if on the not-yet-released versions.

**Comment by flouc001** [comment] 2017-08-24 15:47
@JasonDyalog thank you for noticing the version. @abrudz I cannot reproduce this in the latest RIDE4 build. I'm aware it is an issue in the master branch and a fix is in place in the styling branch a13a3ce. The fix will be merged in with the styling branch when appropriate.

**Comment by jayfoad** [comment] 2017-10-17 09:07
I can't reproduce it either.

**Closed by jayfoad** 2017-10-17 09:07 UTC
